version: "3"

services:
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./client/:/var/www/client
            - ./docker/nginx/app.conf:/etc/nginx/conf.d/app.conf
            - ./docker/nginx/log:/var/log/nginx

    client:
        build: ./docker/client
        environment:
            CLIENT_ENV: ${CLIENT_ENV}
        ports:
            - "${CLIENT_EXTERNAL_PORT}:8000"
        volumes:
            - ./client:/srv/client
        tty: true
